version: 2.0

stylesheets:
  - { path: package://multi_data_monitor/css/plugins/simple.css, target: Simple }

widgets:
  - { class: Simple, input: s1 }

streams:
  - { class: subscription, label: s1, topic: /racing_kart/gnss, field: posmode }
