version: 2.0

stylesheets:
  - { path: "package://multi_data_monitor/css/plugins/simple.css", target: Simple }
  - { path: "package://multi_data_monitor/css/plugins/titled.css", target: Titled }
  - { path: "package://multi_data_monitor/css/colors.css" }


widgets:
  - class: Matrix 
    cols: 1
    items:
      - class: Simple
        value: Kart
        # attrs: { color: magenta }

      - class: Matrix
        cols: 3
        items:
          - throttle
          - brake 
          - steering 

      - class: Simple 
        const: Actuation Cmd

      - class: Matrix
        cols: 3
        items:
          - speed
          - acceleration
          - steering_tire_angle
          - control-mode
          - emergency
          # - joy-delay
          # - posmode

  - class: Titled
    label: throttle 
    title: Accel Pedal
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.accel_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - { class: SetIf, type: real, ge: 0.95, attrs: { back-color: cyan }  }

  - class: Titled
    label: brake 
    title: Brake Pedal 
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.brake_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - { class: SetIf, type: real, ge: 0.95, attrs: { back-color: cyan }  }

  - class: Titled
    label: steering 
    title: Steering Cmd  
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.steer_cmd}
    rules:
      - { class: Precision, digits: 5 }

  - class: Titled
    label: speed 
    title: Speed[km/h]
    input: control_cmd_kph 
    rules:
      - { class: Precision, digits: 2 }
      # - { class: SetIf, type: real, ge: 0.95, attrs: { back-color: cyan }  }

  - class: Titled
    label: acceleration 
    title: Acceleration[m/ss]
    input: { class: subscription, topic: /control/command/control_cmd, field: longitudinal.acceleration}
    rules:
      - { class: Precision, digits: 2 }
      # - { class: SetIf, type: real, ge: 0.95, attrs: { back-color: cyan }  }

  - class: Titled
    label: steering_tire_angle 
    title: Steering Cmd  
    input: { class: subscription, topic: /control/command/control_cmd, field: lateral.steering_tire_angle}
    rules:
      - { class: Precision, digits: 5 }

  - class: Titled
    label: control-mode
    title: Control Mode
    input: { class: subscription, topic: /vehicle/status/control_mode, field: mode }
    rules:
      class: SetFirstIf
      type: uint
      list:
        - { eq: 0, value: NO_COMMAND,       attrs: { back-color: red } }
        - { eq: 1, value: AUTONOMOUS,       attrs: { back-color: cyan } }
        - { eq: 2, value: AUTONOMOUS_STEER_ONLY,   attrs: { back-color: lime } }
        - { eq: 3, value: AUTONOMOUS_VELOCITY_ONLY,   attrs: { back-color: lime } }
        - { eq: 4, value: MANUAL,       attrs: { back-color: yellow } }
        - { eq: 5, value: DISENGAGED,  attrs: { back-color: red } }
        - { eq: 6, value: NOT_READY,  attrs: { back-color: red } }

  - class: Titled
    label: emergency
    title: Emergency
    input: { class: subscription, topic: /racing_kart/debug/status, field: emergency }
    rules:
      class: SetFirstIf
      type: text
      list:
        - { eq: false, value: False,       attrs: { back-color: cyan } }
        - { eq: true, value: True,       attrs: { back-color: red } }

streams:
  - { label: control_cmd_mps, class: subscription, topic: /control/command/control_cmd, field: longitudinal.speed }
  - { label: control_cmd_kph, class: apply, input: control_cmd_mps, rules: f1 }

filters:
  - { class: Units, label: f1, mode: mps_to_kph }

  # - class: Titled
  #   label: joy-delay
  #   title: Joy Delay [sec]
  #   input: { class: subscription, topic: /racing_kart/debug/delay, field: data@1}
  #   rules:
  #     - { class: Precision, digits: 2 }

  # - class: Titled
  #   label: posmode
  #   title: Posmode
  #   input: { class: subscription, topic: /racing_kart/gnss, field: posmode }
  #   rules:
  #     class: SetFirstIf
  #     type: uint
  #     list:
  #       - { eq: 45, value: No Data,      attrs: { back-color: red } }
  #       - { eq: 78, value: No Fix,       attrs: { back-color: red } }
  #       - { eq: 69, value: Estimated,    attrs: { back-color: yellow } }
  #       - { eq: 65, value: Autonomous,   attrs: { back-color: yellow } }
  #       - { eq: 68, value: Differential, attrs: { back-color: yellow } }
  #       - { eq: 70, value: RTK float,    attrs: { back-color: lime } }
  #       - { eq: 82, value: RTK fixed,    attrs: { back-color: cyan } }
