/**:
  ros__parameters:
    # Use true when AWSIM(Simulator) is used
    # specific_covariance: false
    # ONLY FOR SPECIFIC COVARIANCE
    position_0_cov: 0.1
    position_1_cov: 0.1
    position_2_cov: 0.1
    orientation_0_cov: 100000.0 
    orientation_1_cov: 100000.0 
    orientation_2_cov: 100000.0 
