/**:
  ros__parameters:
    goal.position.x: 89653.7
    goal.position.y: 43122.5
    goal.position.z: 0.0
    goal.orientation.x: 0.0
    goal.orientation.y: 0.0
    goal.orientation.z: -0.971732
    goal.orientation.w: 0.236088
