/**:
  ros__parameters:
    update_rate: 20.0
    map_frame_id: "map"
    costmap_center_frame_id: "base_link"
    costmap_width: 50.0
    costmap_resolution: 0.2
    multi_layered_costmap:
      layers:
        - "cached_lanelet_layer"
        - "predicted_object_layer"
      cached_lanelet_layer:
        type: "cached_lanelet"
        map_topic: "/map/vector_map"
        costmap_topic: "~/debug/cached_costmap"
        cached_costmap:
          min_x: 89607.0
          max_x: 89687.0
          min_y: 43114.0
          max_y: 43194.0
          resolution: 0.1
      predicted_object_layer:
        type: "predicted_object"
        predicted_objects_topic: "/perception/object_recognition/objects"
        distance_threshold: 1.2
