/**:
  ros__parameters:
      # mppi
      horizon : 25
      num_samples : 3000
      u_min : [-2.0, -0.35] # accel(m/s2), steer angle(rad)
      u_max : [2.0, 0.35]
      sigmas : [0.5, 0.25] # sample range
      lambda : 1.0 
      auto_lambda : false
      # reference path
      DL : 0.1
      lookahead_distance : 0.1
      reference_path_interval : 0.8
      # cost weights
      Qc : 20.0
      Ql : 1.0
      Qv : 2.0
      Qo : 10000.0
      Qin : 0.01
      Qdin : 0.5
      # model param
      delta_t : 0.1
      vehicle_L : 1.0
      V_MAX : 8.0

