pkill -9 robot_state_pub
pkill -9 vehicle_velocit
pkill -9 imu_gnss_poser_
pkill -9 twist2accel
pkill -9 empty_objects_p
pkill -9 goal_pose_visua
pkill -9 path_to_traject
pkill -9 goal_pose_sette
pkill -9 ros2
pkill -9 python3
pkill -9 rviz2
pkill -9 ekf_localizer
pkill -9 mission_planner
pkill -9 component_conta
pkill -9 simple_pure_pur
pkill -9 initial_pose_ad
pkill -9 routing_adaptor
