/**:
  ros__parameters:
    goal.position.x: 89653.7
    goal.position.y: 43122.5
    goal.position.z: 0.0
    goal.orientation.x: 0.0
    goal.orientation.y: 0.0
    goal.orientation.z: -0.971732
    goal.orientation.w: 0.236088

    half_goal.position.x: 89657.0
    half_goal.position.y: 43175.0
    half_goal.position.z: -28.0
    half_goal.orientation.x: 0.0
    half_goal.orientation.y: 0.0
    half_goal.orientation.z: -0.9
    half_goal.orientation.w: 0.25

    pit_goal.position.x: 89626.3671875
    pit_goal.position.y: 43134.921875
    pit_goal.position.z: 42.10000228881836
    pit_goal.orientation.x: 0.0
    pit_goal.orientation.y: 0.0
    pit_goal.orientation.z: -0.8788172006607056
    pit_goal.orientation.w: -0.47715866565704346

    goal_range: 10.0

    enable_pit: false
    pit_in_threshold: 10
