/**:
  ros__parameters:
    goal.position.x: 89653.7
    goal.position.y: 43122.5
    goal.position.z: 0.0
    goal.orientation.x: 0.0
    goal.orientation.y: 0.0
    goal.orientation.z: -0.971732
    goal.orientation.w: 0.236088

    half_goal.position.x: 89657.0
    half_goal.position.y: 43175.0
    half_goal.position.z: -28.0
    half_goal.orientation.x: 0.0
    half_goal.orientation.y: 0.0
    half_goal.orientation.z: -0.9
    half_goal.orientation.w: 0.25

    pit_stop_area.position.x: 89626.3671875
    pit_stop_area.position.y: 43134.921875
    pit_stop_area.position.z: 42.10000228881836
    pit_stop_area .orientation.x: 0.0
    pit_stop_area.orientation.y: -0.0
    pit_stop_area.orientation.z: -0.878817200660705
    pit_stop_area.orientation.w: -0.47715866565704346
    pit_stop_area.size.x: 4.0
    pit_stop_area.size.y: 2.0

    goal_range: 10.0
