/**:
  ros__parameters:
    pid_d_delay_compensation_time: 0.17

    pid_s_enable_smooth_stop: true
    pid_s_enable_overshoot_emergency: true
    pid_s_enable_large_tracking_error_emergency: true
    pid_s_enable_slope_compensation: false
    pid_s_enable_keep_stopped_until_steer_convergence: true

    # state transition
    pid_d_drive_state_stop_dist: 0.5
    pid_s_drive_state_offset_stop_dist: 1.0
    pid_d_stopping_state_stop_dist: 0.49
    pid_d_stopped_state_entry_duration_time: 0.1
    pid_d_stopped_state_entry_vel: 0.1
    pid_d_stopped_state_entry_acc: 0.1
    pid_d_emergency_state_overshoot_stop_dist: 1.5
    pid_d_emergency_state_traj_trans_dev: 3.0
    pid_d_emergency_state_traj_rot_dev: 0.7

    # drive state
    pid_d_kp: 1.0
    pid_d_ki: 0.1
    pid_d_kd: 0.0
    pid_d_max_out: 1.0
    pid_d_min_out: -1.0
    pid_d_max_p_effort: 1.0
    pid_d_min_p_effort: -1.0
    pid_d_max_i_effort: 0.3
    pid_d_min_i_effort: -0.3
    pid_d_max_d_effort: 0.0
    pid_d_min_d_effort: 0.0
    pid_s_lpf_vel_error_gain: 0.9
    pid_d_current_vel_threshold_pid_integration: 0.5

    pid_s_enable_brake_keeping_before_stop: false
    pid_s_brake_keeping_acc: -0.2

    # smooth stop state
    pid_d_smooth_stop_max_strong_acc: -0.5
    pid_d_smooth_stop_min_strong_acc: -1.0
    pid_d_smooth_stop_weak_acc: -0.3
    pid_d_smooth_stop_weak_stop_acc: -0.8
    pid_d_smooth_stop_strong_stop_acc: -3.4
    pid_d_smooth_stop_max_fast_vel: 0.5
    pid_d_smooth_stop_min_running_vel: 0.01
    pid_d_smooth_stop_min_running_acc: 0.01
    pid_d_smooth_stop_weak_stop_time: 0.8
    pid_d_smooth_stop_weak_stop_dist: -0.3
    pid_d_smooth_stop_strong_stop_dist: -0.5

    # stopped state
    pid_d_stopped_vel: 0.0
    pid_d_stopped_acc: -3.4
    pid_d_stopped_jerk: -5.0

    # emergency state
    pid_d_emergency_vel: 0.0
    pid_d_emergency_acc: -5.0
    pid_d_emergency_jerk: -3.0

    # acceleration limit
    pid_s_max_acc: 3.0
    pid_d_min_acc: -5.0

    # jerk limit
    pid_d_max_jerk: 2.0
    pid_d_min_jerk: -5.0

    # pitch
    pid_s_use_trajectory_for_pitch_calculation: false
    pid_s_lpf_pitch_gain: 0.95
    pid_d_max_pitch_rad: 0.1
    pid_d_min_pitch_rad: -0.1
